### ISSUE TITLE
How to add "Methyl" group and "Acetyl" group " into database?

### ISSUE THREAD

**Issue by zk3353619** [mobiusklein/glycresoft#10]
Hi Joshua,
When I was "Building a Combinatorial Glycan Hypothesis", it's difficult to add the "Methyl" group and "Acetyl" group into the hypothesis---Is there a method to add these two compositions into database?
![image](https://user-images.githubusercontent.com/76904155/103477585-47b36000-4dfb-11eb-83a1-52ba982c63ea.png)

**Comment by zk3353619** [comment]
Hi Joshua,
When I Add Sample To Workspace, it filed to add the MZML  file into the soft! I used the MSConvert to convert the wiff file into MZML, so I do not if that is a reason to cause upload failure. The code returns the errors like below:

20:18:44 - root:process      :114  - INFO - Task Running on PID 111204
20:18:44 - glycresoft_app.task.preprocess_mzml:task_process :78   - INFO - Begin Scan Interpolation
20:18:44 - task_process:task_process :177  - ERROR - UserIdentity(id='', info=UserMetadataBundle({}))@None:error - 'Traceback (most recent call last):
  File "C:\Users\Joshua\miniconda2\envs\glycresoft-deploy\lib\site-packages\glycresoft_app-0.4.3-py2.7.egg\glycresoft_app\task\task_process.py", line 78, in configure_log_wrapper
  File "C:\Users\Joshua\miniconda2\envs\glycresoft-deploy\lib\site-packages\glycresoft_app-0.4.3-py2.7.egg\glycresoft_app\task\preprocess_mzml.py", line 34, in preprocess
  File "C:\Users\Joshua\miniconda2\envs\glycresoft-deploy\lib\site-packages\ms_deisotope-0.0.20-py2.7-win-amd64.egg\ms_deisotope\data_source\infer_type.py", line 89, in MSFileLoader
  File "C:\Users\Joshua\miniconda2\envs\glycresoft-deploy\lib\site-packages\ms_deisotope-0.0.20-py2.7-win-amd64.egg\ms_deisotope\data_source\mzml.py", line 698, in __init__
  File "C:\Users\Joshua\miniconda2\envs\glycresoft-deploy\lib\site-packages\ms_deisotope-0.0.20-py2.7-win-amd64.egg\ms_deisotope\data_source\mzml.py", line 50, in __init__
  File "C:\Users\Joshua\miniconda2\envs\glycresoft-deploy\lib\site-packages\pyteomics\mzml.py", line 105, in __init__
  File "C:\Users\Joshua\miniconda2\envs\glycresoft-deploy\lib\site-packages\pyteomics\xml.py", line 1154, in __init__
  File "C:\Users\Joshua\miniconda2\envs\glycresoft-deploy\lib\site-packages\pyteomics\auxiliary\file_helpers.py", line 375, in __init__
  File "C:\Users\Joshua\miniconda2\envs\glycresoft-deploy\lib\site-packages\pyteomics\xml.py", line 1026, in __init__
  File "C:\Users\Joshua\miniconda2\envs\glycresoft-deploy\lib\site-packages\pyteomics\auxiliary\file_helpers.py", line 82, in wrapped
  File "C:\Users\Joshua\miniconda2\envs\glycresoft-deploy\lib\site-packages\pyteomics\auxiliary\file_helpers.py", line 534, in _build_index
  File "C:\Users\Joshua\miniconda2\envs\glycresoft-deploy\lib\site-packages\ms_deisotope-0.0.20-py2.7-win-amd64.egg\ms_deisotope\data_source\mzml.py", line 93, in _read_byte_offsets
  File "C:\Users\Joshua\miniconda2\envs\glycresoft-deploy\lib\site-packages\pyteomics\xml.py", line 1135, in _read_byte_offsets
  File "C:\Users\Joshua\miniconda2\envs\glycresoft-deploy\lib\site-packages\pyteomics\auxiliary\file_helpers.py", line 489, in _byte_offset_filename
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-10: ordinal not in range(128)

**Comment by mobiusklein** [comment]
To add floating substituents to a glycan composition, you need to prefix their names with an `@` and write them lower-case. The names `@acetyl` and `@methyl` should work. You can add arbitrary named chemical compositions with the following notation: `#<name>#<formula>`.

In my email notification,  I saw another message from you about adding an mzML file to a project, but I don't see it on GitHub itself. Was that issue removed?

**Comment by zk3353619** [comment]
Thank you so much for your quick reply! Your advices worked successfully. And the second question has been solved. 

Here is another issue I want to discussed with you: Now I want to use the GlycReSoft to analyze the LC-MS data from plant polysaccharide: 1). Do you have any suggestions or a advices for this? 2). Is this analysis appropriate? As we know the GlycResoft was designed for N-glycan.

**Comment by mobiusklein** [comment]
Plant polysaccharides as in plant N-glycans? It's certainly doable. Plants have different glycan biosynthesis pathways, but the chitobiose core is still there. You can use this combinatorial hypothesis:
```
Hex 2 7
HexNAc 2 6
dHex 0 3
Xyl 0 1

HexNAc >= dHex
```

If you're trying to analyze the really long mostly linear polysaccharide chains, it is a bit harder. If you have a specific taxonomic ID, you could use the command line client to query glySpace for glycans belonging to a specific taxonomic tree:
`glycresoft build-hypothesis glycan-glyspace -t <taxon-id> -i path/to/file.db` though this is liable to not produce a comprehensive database either.

If you're familiar with Python, you can write an arbitrary program in Python using `glypy` to build a hypothesis text file with one glycan composition per line of a file. Similarly, you could download a curated list from https://glyconnect.expasy.org/browser/taxonomy and use `glypy.io.glyconnect` to parse it into the appropriate format.

**Comment by mobiusklein** [comment]
Did this resolve the problem you were facing?
