### ISSUE TITLE
Error when run the search-glycan

### ISSUE THREAD

**Issue by bobaoai** [mobiusklein/glycresoft#8]
Hi Joshua,

Thanks for the help through email. But I have error when I run the glycresoft analyze search-glycan here. I cloned the latest glycresoft and make it on Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-130-generic x86_64). Could you help check it thanks!

Bokan

```
glycresoft mzml preprocess \
--mass-offset -311.17 \
--averagine glycan \
--maximum-charge 4 \
--name "20190205_TK-EPO_Expres2ion_04" \
--processes 10 \
--background-reduction 5 \
--start-time 12 \
"./glycretest/20190205_TK-EPO_Expres2ion_04.mzXML" \
"test_off.mzML"

glycresoft build-hypothesis glycan-glyspace \
-m n-linked \
-t 10029 \
glyspace-glycans.db \
-n "CHO N-Linked Glycans"


glycresoft analyze search-glycan \
-a Formate 1 \
-f formate-adduct-model \
-o test_nooff_search.db \
-m 6e-4 \
glyspace-glycans.db \
test_off.mzML "CHO N-Linked Glycans" \
--export csv



{'analysis': None,
 'analysis_name': u'20190205_TK-EPO_Expres2ion_04 @ CHO N-Linked Glycans',
 'database_connection': u'glyspace-glycans.db',
 'delta_rt': 0.5,
 'grouping_error_tolerance': 1.5e-05,
 'hypothesis_id': 1,
 'mass_error_tolerance': 0.0006,
 'mass_shifts': [MassShift(Formate, Composition({'H': 2, 'C': 1, 'O': 2}))],
 'minimum_mass': 500.0,
 'msn_mass_error_tolerance': 2e-05,
 'n_processes': 4,
 'network': None,
 'output_path': u'test_nooff_search.db',
 'regularization_model': None,
 'regularize': None,
 'require_msms_signature': 0.0,
 'sample_path': 'test_off.mzML',
 'sample_run_id': -1,
 'scoring_model': ChromatogramScorer('line_score': <glycan_profiling.scoring.shape_fitter.ChromatogramShapeModel object at 0x7f0da0cb3690>, 'isotopic_fit': <glycan_profiling.scoring.isotopic_fit.IsotopicPatternConsistencyModel object at 0x7f0da0cb36d0>, 'spacing_fit': <glycan_profiling.scoring.spacing_fitter.ChromatogramSpacingModel object at 0x7f0da0cb3710>, 'charge_count': <glycan_profiling.scoring.base.CompositionDispatchingModel object at 0x7f0da1178250>, 'mass_shift_score': <glycan_profiling.models.mass_shift_models.GeneralizedFormateMassShiftModel object at 0x7f0da0cc6610>),
 'start_time': datetime.datetime(2019, 4, 11, 0, 8, 26, 868321),
 'status': 'started'}
00:08:29 - glycresoft:profiler     :458  - INFO - The smallest possible database mass is 910.327780, raising the minimum mass to extract.
00:08:29 - glycresoft:process      :53   - INFO - Begin Matching Chromatograms
00:08:29 - glycresoft:extract      :75   - INFO - ... Begin Extracting Chromatograms
00:09:04 - glycresoft:extract      :77   - INFO - ...... Aggregating Chromatograms
00:09:04 - glycresoft:extract      :56   - INFO - ... 382 Chromatograms Extracted.
00:09:04 - glycresoft:match        :286  - INFO - Matching Chromatograms
00:09:04 - glycresoft:match        :305  - INFO - Handling mass_shifts
00:09:04 - glycresoft:match        :180  - INFO - Begin Forward Search
00:09:04 - glycresoft:match        :123  - INFO - Begin Reverse Search
00:09:04 - glycresoft:match        :233  - INFO - Building Connected Components
00:09:04 - glycresoft:match        :239  - INFO - Validating 59 Components
00:09:04 - glycresoft:process      :55   - INFO - End Matching Chromatograms
00:09:04 - glycresoft:process      :56   - INFO - 83 Chromatogram Candidates Found
00:09:04 - glycresoft:process      :60   - INFO - Begin Evaluating Chromatograms
00:09:39 - glycresoft:evaluate     :138  - INFO - Collapsing Duplicates
00:09:40 - glycresoft:evaluate     :91   - INFO - Pruning mass shift branches
00:09:40 - glycresoft:evaluate     :93   - INFO - Re-evaluating after mass shift pruning
00:09:41 - glycresoft:evaluate     :138  - INFO - Collapsing Duplicates
00:09:41 - glycresoft:process      :73   - INFO - End Evaluating Chromatograms
00:09:41 - glycresoft:profiler     :506  - INFO - Saving solutions
00:09:41 - glycresoft:analysis_migr:231  - INFO - Migrating Hypothesis
<SQLITE3-LOG> (2067) abort at 21 in [INSERT INTO "GlycanHypothesis" (name, uuid, parameters, status) VALUES (?, ?, ?, ?)]: UNIQUE constraint failed: GlycanHypothesis.name
Traceback (most recent call last):
  File "/home/bokan/miniconda2/bin/glycresoft", line 11, in <module>
    load_entry_point('glycan-profiling==0.3.12', 'console_scripts', 'glycresoft')()
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/glycan_profiling-0.3.12-py2.7-linux-x86_64.egg/glycan_profiling/cli/__main__.py", line 39, in main
    base.cli.main(standalone_mode=True)
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/glycan_profiling-0.3.12-py2.7-linux-x86_64.egg/glycan_profiling/cli/analyze.py", line 573, in search_glycan
    analyzer.start()
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/glycan_profiling-0.3.12-py2.7-linux-x86_64.egg/glycan_profiling/task.py", line 299, in start
    out = self.run()
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/glycan_profiling-0.3.12-py2.7-linux-x86_64.egg/glycan_profiling/profiler.py", line 465, in run
    self.save_solutions(proc.solutions, extractor, database, proc.evaluator)
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/glycan_profiling-0.3.12-py2.7-linux-x86_64.egg/glycan_profiling/profiler.py", line 528, in save_solutions
    exporter.run()
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/glycan_profiling-0.3.12-py2.7-linux-x86_64.egg/glycan_profiling/database/analysis/analysis_migration.py", line 232, in run
    self.migrate_hypothesis()
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/glycan_profiling-0.3.12-py2.7-linux-x86_64.egg/glycan_profiling/database/analysis/analysis_migration.py", line 269, in migrate_hypothesis
    self.glycan_db.hypothesis)
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/glycan_profiling-0.3.12-py2.7-linux-x86_64.egg/glycan_profiling/database/builder/glycan/migrate.py", line 39, in migrate_hypothesis
    self.session.flush()
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2446, in flush
    self._flush(objects)
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2584, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2544, in _flush
    flush_context.execute()
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 416, in execute
    rec.execute(self)
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 583, in execute
    uow,
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1116, in _emit_insert_statements
    statement, params
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 980, in execute
    return meth(self, multiparams, params)
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1099, in _execute_clauseelement
    distilled_params,
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1240, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "/home/bokan/miniconda2/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (pysqlite2.dbapi2.IntegrityError) UNIQUE constraint failed: GlycanHypothesis.name [SQL: u'INSERT INTO "GlycanHypothesis" (name, uuid, parameters, status) VALUES (?, ?, ?, ?)'] [parameters: (u'CHO N-Linked Glycans', '23369c6ae7bd4b6fa3a70db47466c856', <read-only buffer for 0x7f0d8a08ea80, size -1, offset 0 at 0x7f0d8944faf0>, u'complete')] (Background on this error at: http://sqlalche.me/e/gkpj)
bokan@jabba:/data/bokan$ 
```

**Comment by mobiusklein** [comment]
This message is telling you that the output file path already contains that hypothesis. `glycresoft` does not overwrite its output files, but tries to add them. The output file is an SQLite database. You'll need to specify  different output path, or delete the existing file.

I'll try to add some warning messages when it detects that the output path already exists.

**Comment by bobaoai** [comment]
Yeah, it works. Thanks, Joshua!
